name: Get data

on:
    workflow_dispatch:

permissions:
    contents: write

jobs:
    get_data:
        runs-on: ubuntu-latest

        steps:
            - name: install nodejs
              uses: actions/setup-node@v4
              with:
                  node-version: 25

            - name: Checkout repo
              uses: actions/checkout@v4

            - name: run script
              run: |
                  sudo apt update
                  sudo apt install -y jq zip

                  node dp-scraper.mjs
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_PAT }}

            - name: find and zip data folder
              run: |
                  set -e

                  DATA_DIR=""

                  for dir in "./data" "../data"; do
                    if [ -d "$dir" ]; then
                      DATA_DIR="$dir"
                      break
                    fi
                  done

                  if [ -z "$DATA_DIR" ]; then
                    echo "No data directory found"
                    exit 1
                  fi

                  echo "Found data dir: $DATA_DIR"

                  ZIP_NAME="data-archive.zip"

                  cd "$(dirname "$DATA_DIR")"
                  zip -r "$GITHUB_WORKSPACE/$ZIP_NAME" "$(basename "$DATA_DIR")"

            - name: upload zipped artifact
              uses: actions/upload-artifact@v4
              with:
                  name: scraped-data
                  path: data-archive.zip
                  retention-days: 30
                  if-no-files-found: error
                  compression-level: 0

            - name: set git config
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

            - name: commit & push
              run: |
                  git add --all || echo "failed to add files"

                  git commit -m "chore: add data" || echo "nothing to commit"

                  git push || echo "failed to push"
