name: Get data

on:
    workflow_dispatch:
    schedule: 
        - cron: "*/5 * * * *"

permissions:
    contents: write

jobs:
    get_data:
        runs-on: ubuntu-latest

        steps:
            - name: install nodejs
              uses: actions/setup-node@v4
              with:
                  node-version: 25

            - name: Checkout repo
              uses: actions/checkout@v4

            - name: run script
              run: |
                  sudo apt update
                  sudo apt install -y jq zip

                  bash changelogs.sh
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_PAT }}

     
            - name: set git config
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

            - name: commit & push
              run: |
                  git add --all || echo "failed to add files"

                  git commit -m "chore: update changelogs history" || echo "nothing to commit"

                  git push || echo "failed to push"
